Portfolio_Core_Project/Controllers/ExperienceController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Portfolio_Core_Project.Controllers
{
    //[Authorize(Roles ="Admin")]
    public class ExperienceController : Controller
    {
        ExperienceManager experienceManager = new ExperienceManager(new EfExperienceDal());
        public IActionResult Index()
        {
            ViewBag.v1 = "Deneyim Listesi";
            ViewBag.v2 = "Deneyimler";
            ViewBag.v3 = "Deneyim Listesi";
            var values = experienceManager.TGetList();
            return View(values);
        }

        [HttpGet]
        public IActionResult AddExperience()
        {
            ViewBag.v1 = "Deneyim Ekleme";
            ViewBag.v2 = "Deneyimler";
            ViewBag.v3 = "Deneyim Ekleme";
            return View();
        }
        [HttpPost]
        public IActionResult AddExperience(Experience experience)
        {
            experienceManager.TAdd(experience);
            return RedirectToAction("Index");
        }
        public IActionResult DeleteExperience(int id)
        {
            var values = experienceManager.TGetByID(id);
            experienceManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditExperience(int id)
        {
            ViewBag.v1 = "Deneyim Güncelleme";
            ViewBag.v2 = "Deneyimler";
            ViewBag.v3 = "Deneyim Güncelleme";
            var values = experienceManager.TGetByID(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditExperience(Experience experience)
        {
            experienceManager.TUpdate(experience);
            return RedirectToAction("Index");
        }
    }
}

Portfolio_Core_Project/Views/Experience/AddExperience.cshtml
@model EntityLayer.Concrete.Experience
@{
    ViewData["Title"] = "AddExperience";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@* <div class="card-header border-0">
    <h3 class="mb-0">Deneyim Ekleme Sayfası</h3>
</div>

@using (Html.BeginForm("AddExperience", "Experience", FormMethod.Post))
{
    <br />
    @Html.Label("Deneyim Başlığı")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />
    <label>Tarih</label>
    @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
    <br />
    <label>Resim Yolu</label>
    @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
    <br />
    <label>Açıklama</label>
    @Html.TextAreaFor(x => x.Description,10,3, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Deneyim Ekle</button>
} *@

@using (Html.BeginForm("AddExperience", "Experience", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Deneyim Ekleme Paneli</h4>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>Başlık</label>
                        <input type="text" class="form-control" name="Name">
                    </div>
                    <div class="form-group">
                        <label>Tarih</label>
                        <input type="text" class="form-control" name="Date">
                    </div>
                    <div class="form-group">
                        <label>Görsel Url</label>
                        <input type="text" class="form-control" name="ImageUrl">
                    </div>
                    <div class="form-group">
                        <label for="exampleTextarea1">Açıklama</label>
                        <textarea class="form-control" name="Description" rows="6"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button class="btn btn-dark">İptal</button>
                </form>
            </div>
        </div>
    </div>
}

Portfolio_Core_Project/Views/Experience/EditExperience.cshtml
@model EntityLayer.Concrete.Experience
@{
    ViewData["Title"] = "EditExperience";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@* <div class="card-header border-0">
    <h3 class="mb-0">Deneyim Güncelleme Sayfası</h3>
</div>

@using (Html.BeginForm("EditExperience", "Experience", FormMethod.Post))
{
    @Html.HiddenFor(x => x.ExperienceID)
    <br />
    @Html.Label("Deneyim Başlığı")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />
    <label>Tarih</label>
    @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
    <br />
    <label>Resim Yolu</label>
    @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
    <br />
    <label>Açıklama</label>
    @Html.TextAreaFor(x => x.Description, 10, 3, new { @class = "form-control" })
    <br />
    <button class="btn btn-outline-success">Güncelle</button>
}
 *@

 @using (Html.BeginForm("EditExperience", "Experience", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Deneyim Düzenleme Paneli</h4>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>ID</label>
                        @Html.TextBoxFor(x => x.ExperienceID, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Başlık</label>
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Tarih</label>
                        @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Görsel Url</label>
                        @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleTextarea1">Açıklama</label>
                        @Html.TextAreaFor(x => x.Description, 10, 3, new { @class = "form-control" })
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button class="btn btn-dark">İptal</button>
                </form>
            </div>
        </div>
    </div>
}

Portfolio_Core_Project/Views/Experience/Index.cshtml
@using EntityLayer.Concrete
@model List<Experience>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@* <div class="card-header border-0">
    <h3 class="mb-0">Deneyim Listesi</h3>
</div>
<!-- Light table -->
<div class="table-responsive">
    <table class="table align-items-center table-flush">
        <thead class="thead-light">
            <tr>
                <th scope="col" class="sort" data-sort="name">#</th>
                <th scope="col" class="sort" data-sort="budget">Başlık</th>
                <th scope="col" class="sort" data-sort="status">Title / Tarih</th>
                <th scope="col">Sil</th>
                <th scope="col" class="sort" data-sort="completion">Düzenle</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody class="list">
            @foreach (var item in Model)
            {
                <tr>
                    <th>
                        @item.ExperienceID
                    </th>
                    <th class="budget">
                        @item.Name
                    </th>

                    <td>
                 @item.Date
                    </td>
                    <td><a href="/Experience/DeleteExperience/@item.ExperienceID" class="btn btn-danger">Sil</a></td>
                    <td><a href="/Experience/EditExperience/@item.ExperienceID" class="btn btn-info">Güncelle</a></td>
                </tr>
            }
        </tbody>
    </table>
    <a href="/Experience/AddExperience/" class="btn btn-primary">Deneyim Ekle</a>
</div> *@

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Deneyimler</h4>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Başlık</th>
                            <th>Title / Tarih</th>
                            <th>Sil</th>
                            <th>Güncelle</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.ExperienceID</td>
                                <td>@item.Name</td>
                                <td>@item.Date</td>
                                <td><a href="/Experience/DeleteExperience/@item.ExperienceID" class="btn btn-outline-danger">Sil</a></td>
                                <td><a href="/Experience/EditExperience/@item.ExperienceID" class="btn btn-outline-success">Güncelle</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
                <a href="/Experience/AddExperience/" class=" btn btn-outline-info">Yeni Deneyim Ekle</a>
            </div>
        </div>
    </div>
</div>