Portfolio_Core_Project/Controllers/ContactSubplaceController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Portfolio_Core_Project.Controllers
{
    public class ContactSubplaceController : Controller
    {
        ContactManager contactManager = new ContactManager(new EfContactDal());

        [HttpGet]
        public IActionResult Index()
        {
            var values = contactManager.TGetByID(1);
            return View(values);
        }
        [HttpPost]
        public IActionResult Index(Contact contact)
        {
            contactManager.TUpdate(contact);
            return RedirectToAction("Index", "Default");
        }
    }
}

Portfolio_Core_Project/Views/ContactSubplace/Index.cshtml
@model EntityLayer.Concrete.Contact
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@using (Html.BeginForm("Index", "ContactSubplace", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Alt İletişim Bilgileri Düzenleme Paneli</h4>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>ID</label>
                        @Html.TextBoxFor(x => x.ContactID, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Başlık</label>
                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Telefon</label>
                        @Html.TextBoxFor(x => x.Phone, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Mail</label>
                        @Html.TextBoxFor(x => x.Mail, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleTextarea1">Açıklama</label>
                        @Html.TextAreaFor(x => x.Description, 10, 3, new { @class = "form-control" })
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button class="btn btn-dark">İptal</button>
                </form>
            </div>
        </div>
    </div>
}